theme = "autumn"

[editor]
true-color = true

[keys.normal]
ret = ["insert_newline", "normal_mode"]
backspace = "delete_char_backward"
C-p = "save_selection"
C-s = ":w"

[keys.insert]
C-s = [":w", "normal_mode"]
